<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <Version></Version>
	  <AssemblyVersion></AssemblyVersion>
	  <Authors>naz-hage</Authors>
	  <Company>naz-hage</Company>
	  <Product>Build automation</Product>
	  <Copyright>2020-XXXX</Copyright>
  </PropertyGroup>

  <PropertyGroup>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	<AssemblyName>nb</AssemblyName>
  </PropertyGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="nbtests" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="resources\common.targets" />
		<EmbeddedResource Include="resources\dotnet.targets" />
		<EmbeddedResource Include="resources\mongodb.targets" />
		<EmbeddedResource Include="resources\nbuild.targets" />
		<EmbeddedResource Include="resources\node.targets" />
		<EmbeddedResource Include="resources\nuget.targets">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
		<None Include="..\go\apps.json" CopyToOutputDirectory="PreserveNewest" Link="apps.json" />
	</ItemGroup>

	<ItemGroup>
	<PackageReference Include="System.CommandLine" Version="2.0.11" />
	</ItemGroup>
 <ItemGroup>
    <ProjectReference Include="..\GitHubRelease\GitHubRelease.csproj" />
    <ProjectReference Include="..\NbuildTasks\NbuildTasks.csproj" />
  </ItemGroup>

</Project>
