repos:
  # Standard pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=1024']
      - id: mixed-line-ending

  # C# specific hooks
  - repo: https://github.com/dotnet/format
    rev: v5.1.250801
    hooks:
      - id: dotnet-format
        args: ['--include']

  # PowerShell hooks
  - repo: https://github.com/PowerShell/PSScriptAnalyzer
    rev: 1.21.0
    hooks:
      - id: powershell-script-analyzer

  # Custom hook for updating documentation versions
  - repo: local
    hooks:
      - id: update-doc-versions
        name: Update documentation versions
        entry: pwsh
        args: ['-File', 'dev-setup/update-versions.ps1', '-DevSetupPath', 'dev-setup', '-DocsPath', 'docs/ntools/ntools.md']
        language: system
        files: '^dev-setup/.*\.json$'
        pass_filenames: false

  # Commit message validation
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.1.1
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]

# Configuration
default_stages: [commit]
fail_fast: false
