repos:
  # Standard pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=1024']
      - id: mixed-line-ending

  # C# specific hooks
  - repo: https://github.com/dotnet/format
    rev: v5.1.250801
    hooks:
      - id: dotnet-format
        args: ['--include']

  # PowerShell hooks
  - repo: https://github.com/PowerShell/PSScriptAnalyzer
    rev: 1.21.0
    hooks:
      - id: powershell-script-analyzer

  # Custom hook for updating documentation versions (NBuild)
  - repo: local
    hooks:
      - id: nbuild-update-doc-versions
        name: Update Documentation Versions (NBuild)
        entry: nb update_doc_versions
        language: system
        types: [json]
        files: ^dev-setup/.*\.json$
        pass_filenames: false
        always_run: true
        verbose: true

  # Commit message validation
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.1.1
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]

# Configuration
default_stages: [commit]
fail_fast: false
