@echo off
SetLocal EnableDelayedExpansion
set DOTNET_VERSION=8.0.1
set NTOOLS_VERSION=1.2.0
set DEV_DRIVE=c:
set MAIN_DIR=source
:: Check if admin
net session >nul 2>&1
if %errorLevel% == 0 (
    echo Admin rights detected
) else (
    echo Please run this script as an administrator.
    exit /b 1
)
:: Install latest Ntools from github
:: save current directory
set currentdir=%cd%
cd nbuild\resources
powershell.exe -Command ".\install-ntools.ps1" %DOTNET_VERSION% %NTOOLS_VERSION% %DEV_DRIVE% %MAIN_DIR%
:: Restore current directory
cd %currentdir%
:: Delete the installer
del !INSTALLER_PATH!
@REM The .NET Desktop Runtime installer logs its activities to the Windows temporary directory %temp%. The exact location can vary, 
@REM but it's typically in a location similar to this:
@REM ```
@REM C:\Users\YourUsername\AppData\Local\Temp
@REM ```
@REM The log files generated by the installer will have a name like `Microsoft_Windows_Desktop_Runtime_-_8.0.1_(x64)_20240120081951.log` or similar,
@REM  depending on the version you installed and the time of installation.
@REM Please note that the log files are only created if the installer encounters an issue. If the installation is successful, log file may not be created.
EndLocal