site_name: Ntools - Work in Progress
site_description: Software Tools Collection.
site_author: naz-hage
repo_name: ntools
repo_url: https://github.com/naz-hage/ntools
edit_uri: edit/main/docs/

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: blue
      accent: blue

plugins:
  - search

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed
  - pymdownx.details
  - toc:
      permalink: true
      permalink_title: Anchor link to this section for reference

nav:
  - Home: index.md
  - Getting Started:
      - Installation: installation.md
      - Set Up a Project: setup.md
      - Usage Guide: usage.md
  - Using Ntools:
      - SDO CLI: sdo-net.md
      - GitHub Releases: github-release.md
  - Development:
      - Architecture: devops-tools-suite-architecture.md
      - Build Types: buildtypes.md
      - Versioning: versioning.md
      - Version Automation Guide: version-automation-guide.md
      - Development Tools: ntools.md
      - PowerShell Modules:
          - ntools-scripts Module: ntools-scripts-module.md
          - ntools-scripts API: ntools-scripts-module-api.md
  - Build and Test:
      - Custom Build Tasks: nbuildtasks.md
      - MSBuild Targets: nbuild-targets.md
      - Code Coverage: code-coverage.md
  - Reference:
      - Azure DevOps Payloads: azdo_payloads.md
