site_name: Ntools - Work in Progress
site_description: Software Tools Collection.
site_author: naz-hage
repo_name: ntools
repo_url: https://github.com/naz-hage/ntools
edit_uri: edit/main/docs/

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: blue
      accent: blue

plugins:
  - search

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed
  - pymdownx.details
  - toc:
      permalink: true
      permalink_title: Anchor link to this section for reference

nav:
  - Getting Started: 
    - Overview: index.md
    - Architecture: devops-tools-suite-architecture.md
    - Installation: installation.md
    - Practice: usage.md
    - Setup your project: setup.md
    - Build Types: buildtypes.md
    - Versioning: versioning.md
  - List of Tools:
      - Nbuild (nb.exe): nbuild.md
      - lf (lf.exe): lf.md
      - Nbackup (nbackup.exe): nbackup.md
      - Github Release : github-release.md
      - Sdo (sdo.exe):
        - Documentation: sdo-net.md
        - Usage Examples:
          - AzDO Bug Example: issue-azdo-bug-example.md
          - AzDO Epic Example: issue-azdo-epic-example.md
          - AzDO PBI Example: issue-azdo-pbi-example.md
          - AzDO Task Example: issue-azdo-task-example.md
          - GitHub Issue Example: issue-gh-example.md
  - Custom Build Tasks:
      - Nbuild Tasks: nbuildtasks.md
  - Developer setup:
    - Version Automation Guide: version-automation-guide.md
    - Development Tools: ntools.md
    - ntools-scripts module:
      - Module: ntools-scripts-module.md
      - API: ntools-scripts-module-api.md
  - Build System Features:
    - Code Coverage: code-coverage.md
    - MSBuild Targets: nbuild-targets.md
  - Reference:
    - AzDO Payloads: azdo_payloads.md
  - TODO: todo.md
