@echo off
@REM Reference: https://learn.microsoft.com/en-us/visualstudio/msbuild/walkthrough-using-msbuild?view=vs-2022
@REM This script is used to build the project using MSBuild
@REM This file is generated by Nbuild.exe (Do not modify)
@REM for more information, please visit <TBD>
set BUILD_LOG=nbuild.log
set PROJECT=nbuild.targets

if "%1"=="" (
    set CMD=%PROJECT% -fl -flp:logfile=%BUILD_LOG%;verbosity=normal
) else (
    set CMD=%PROJECT% /t:%1 -fl -flp:logfile=%BUILD_LOG%;verbosity=normal
)

msbuild %CMD%
if ERRORLEVEL 1 (
    echo %ERRORLEVEL%
    for /f "tokens=1 delims='" %%G in ('ngit -git getbranch') do echo Branch: %%G
    for /f "tokens=1 delims='" %%G in ('ngit -git gettag') do echo Tag: %%G
    echo %0 '%1' FAILED
    echo %0 '%1' FAILED >>%BUILD_LOG%
    EXIT /B1
) else (
    for /f "tokens=1 delims='" %%G in ('ngit -git getbranch') do echo Branch: %%G
    for /f "tokens=1 delims='" %%G in ('ngit -git gettag') do echo Tag: %%G
    echo %0 '%1' SUCCEEDED 
    echo %0 '%1' SUCCEEDED >>%BUILD_LOG%
)
