@echo off
@REM Reference: https://learn.microsoft.com/en-us/visualstudio/msbuild/walkthrough-using-msbuild?view=vs-2022
@REM This script is used to build the project using MSBuild
@REM This file is generated by Nb.exe (Do not modify)

set BUILD_LOG=nbuild.log
set PROJECT=nbuild.targets

if "%1"=="/?" (
    @REM Display the available targets
    Nb targets
    EXIT /B0
) else if "%1"=="" (
    @REM Set the CMD variable to the project name
    set CMD=%PROJECT% -fl -flp:logfile=%BUILD_LOG%;verbosity=normal
) else (
    @REM Set the CMD variable to the project name and the specified %1 argument
    set CMD=%PROJECT% /t:%1 -fl -flp:logfile=%BUILD_LOG%;verbosity=normal
)

@REM Build the project with MSBuild using the specified %CMD% arguments
msbuild %CMD%
if ERRORLEVEL 1 (
    echo %ERRORLEVEL%
    @REM Display the Git project information: branch and tag
    nb git_info
    echo %0 '%1' FAILED
    echo %0 '%1' FAILED >>%BUILD_LOG%
    EXIT /B1
) else (
    @REM Display the Git project information: branch and tag
    nb git_info
    echo %0 '%1' SUCCEEDED 
    echo %0 '%1' SUCCEEDED >>%BUILD_LOG%
)