name: .Net Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build Type (stage or prod)'
        required: false
        default: 'stage'
  workflow_call:

env:
  Solution_Name: ntools.sln
  Test_Project_Path: LauncherTests
  Build_Type: ${{ github.event.inputs.build_type || 'stage' }}
  Enable_Logging: true # Enable additional logging

jobs:
  build:

    name: Build and Test
    runs-on: windows-latest

    steps:
    - name: Check Build Type | must be stage or prod
      run: |
        if ($env:Build_Type -ne "stage" -and $env:Build_Type -ne "prod") {
          Write-Output "Invalid build type: $env:Build_Type"
          exit 1
        }
      shell: pwsh

    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Install ntools
      run: |
        cd ./DevSetup
        ./install-ntools.ps1
      shell: pwsh
      working-directory: ${{ github.workspace }}

    - name: Set ProgramFiles Path
      run: |
        $programFilesPath = [System.Environment]::GetFolderPath('ProgramFiles')
        echo "ProgramFilesPath=$programFilesPath" | Out-File -FilePath $env:GITHUB_ENV -Append
      shell: pwsh
      working-directory: ${{ github.workspace }}
   
    - name: Configure Git
      run: |
        git config --global user.name "gitHub-actions"
        git config --global user.email "actions@github.com"

    - name: Build using ntools
      run: |
        & "$env:ProgramFilesPath/nbuild/nb.exe" ${{ env.Build_Type }} -v ${{ env.Enable_Logging }}
      shell: pwsh
      working-directory: ${{ github.workspace }}

  docs:
    name: Publish Docs
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
    
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies	
        run: |	
          python -m pip install --upgrade pip	
          pip install mkdocs	
      - name: Update docs	
        run: |	
          mkdocs build	
          mkdocs gh-deploy --force