name: publish-docs
on:
  workflow_run:
    workflows: [dotnet-desktop]  # Chain to the dotnet-desktop workflow
    types:
      - completed
      - successful  # Only trigger on successful completion

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check if previous workflow was successful
        if: github.event.workflow_run.conclusion == 'success'  # Check if the previous workflow was successful
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies  
        run: |  
          python -m pip install --upgrade pip  
          pip install mkdocs  
      - name: Update docs  
        run: |  
          mkdocs build  
          mkdocs gh-deploy --force
