name: Publish Docs
# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]
  # Triggers the workflow on any pull request event
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    integration:
      uses: ./.github/workflows/dotnet-desktop.yml
      permissions:
        contents: read
        checks: write
       
  # This workflow contains a single job called "build"
    build:
      needs: [integration]       
      # The type of runner that the job will run on
      runs-on: ubuntu-latest
      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.12'
        - name: Install dependencies	
          run: |	
            python -m pip install --upgrade pip	
            pip install mkdocs	
        - name: Update docs	
          run: |	
            mkdocs build	
            mkdocs gh-deploy --force
