name: Update Documentation Versions

on:
  push:
    paths:
      - 'dev-setup/*.json'
  pull_request:
    paths:
      - 'dev-setup/*.json'
  workflow_dispatch:

jobs:
  update-versions:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup PowerShell
      shell: pwsh
      run: |
        Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser -Force
        
    - name: Update versions in documentation
      shell: pwsh
      run: |
        cd dev-setup
        .\update-versions.ps1 -DevSetupPath "." -DocsPath "..\docs\ntools\ntools.md"
        
    - name: Check for changes
      id: verify-changed-files
      run: |
        if git diff --quiet; then
          echo "changed=false" >> $GITHUB_OUTPUT
        else
          echo "changed=true" >> $GITHUB_OUTPUT
        fi
      shell: bash
      
    - name: Commit changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/ntools/ntools.md
        git commit -m "Auto-update documentation versions from JSON files"
        
    - name: Push changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.head_ref }}
